[app]
name = "Miner"
category = "Badge"

[entry]
class = "Miner"

[metadata]
author = "pikesley"
license = "MIT"
url = "https://www.github.com/pikesley/tildagon-miner"
description = "Manic Miner sprites wandering around your Tildagon"
version = "0.0.5"
